import { WeddingSettings, CeremonyItem, StoryMilestone, WeddingPhoto, RSVPSubmission } from './types';

export const initialWeddingSettings: WeddingSettings = {
  groom: {
    nameBn: 'অর্ঘ্য দে',
    nameEn: 'Argha De',
    subTitleBn: 'বি.টেক (কম্পিউটার সায়েন্স), সফটওয়্যার আর্কিটেক্ট',
    subTitleEn: 'B.Tech (CSE), Software Architect',
    fatherBn: 'শ্রী সুভাষচন্দ্র রায়',
    fatherEn: 'Sri Subhash Chandra Roy',
    motherBn: 'শ্রীমতি কল্যাণী রায়',
    motherEn: 'Smt. Kalyani Roy',
    grandfatherBn: 'স্বর্গীয় নিশীথকান্ত রায়',
    grandfatherEn: 'Late Nishith Kanta Roy',
    addressBn: '“রায় বাড়ি”, উত্তরপাড়া, হুগলি, পশ্চিমবঙ্গ',
    addressEn: '"Roy Bari", Uttarpara, Hooghly, West Bengal',
    bioBn: 'শান্ত, সংস্কৃতিমনা ও স্বপ্নবান। পরিবার ও সঙ্গীতকে ভালোবাসেন।',
    bioEn: 'Cultured, gentle, and passionate about technology, Indian classical music, and family values.',
    photoUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=700&q=80',
  },
  bride: {
    nameBn: 'অর্পিতা বসু',
    nameEn: 'Arpita Basu',
    subTitleBn: 'এম.এ. (ইংরেজি সাহিত্য), সহকারি অধ্যাপিকা',
    subTitleEn: 'M.A. (English Literature), Assistant Professor',
    fatherBn: 'শ্রী রথীন্দ্রনাথ মুখার্জী',
    fatherEn: 'Sri Rathindranath Mukherjee',
    motherBn: 'শ্রীমতি সুমনা মুখার্জী',
    motherEn: 'Smt. Sumana Mukherjee',
    grandfatherBn: 'স্বর্গীয় হরিশংকর মুখার্জী',
    grandfatherEn: 'Late Harishankar Mukherjee',
    addressBn: '“মুখার্জী কুটির”, বালি, হাওড়া, পশ্চিমবঙ্গ',
    addressEn: '"Mukherjee Kutir", Bally, Howrah, West Bengal',
    bioBn: 'হাসিখুশি, সাহিত্যপ্রেমী এবং রবীন্দ্রসঙ্গীতের অনুরক্ত সাধক।',
    bioEn: 'Cheerful, bibliophile, lover of Rabindra Sangeet, literature, and timeless Bengali traditions.',
    photoUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=700&q=80',
  },
  weddingDate: '2026-12-11T20:25:00',
  weddingDateBn: '২৬শে অগ্রহায়ণ, ১৪৩৩ বঙ্গাব্দ (১৩ই ডিসেম্বর, ২০২৬)',
  weddingDateEn: 'Friday, 13th December, 2026 (26th Agrahayana, 1433)',
  venueNameBn: 'বসু বাড়ি (Basu Bari)',
  venueNameEn: 'Basu Bari',
  venueAddressBn: 'মাতিশ্বর বসুপাড়া পূর্ব বর্ধমান',
  venueAddressEn: 'Matishwar Basupara East Burdwan',
  venueMapsUrl: 'https://maps.app.goo.gl/pNfPZdbKAZdeDfx66',
  googleSheetsWebhookUrl: '',
  contactPhones: [
    { labelBn: 'বরের পরিবার (শ্রী সুভাষ রায়)', labelEn: "Groom's Family (Sri Subhash Roy)", number: '+91 98301 23456' },
    { labelBn: 'কনের পরিবার (শ্রী রথীন মুখার্জী)', labelEn: "Bride's Family (Sri Rathin Mukherjee)", number: '+91 98312 65432' },
    { labelBn: 'অতিথি অভ্যর্থনা ও রুট সহায়তা', labelEn: 'Guest Hospitality & Route Help', number: '+91 98740 99887' },
  ],
};

export const ceremoniesData: CeremonyItem[] = [
  {
    id: 'aiburobhat',
    titleBn: 'আইবুড়ো ভাত ও আশীর্বাদ',
    titleEn: 'Aiburobhat (Pre-Wedding Blessing Feast)',
    subtitleBn: 'কনে ও বরের অবিবাহিত জীবনের অন্তিম প্রীতিভোজ',
    subtitleEn: 'The traditional auspicious feast showered with love from aunts & uncles',
    dateBn: '২৩শে অগ্রহায়ণ, ১৪৩১ (৯ই ডিসেম্বর, ২০২৬)',
    dateEn: 'Wednesday, 9th December, 2026',
    timeBn: 'দুপুর ১২:৩০ ঘটিকা',
    timeEn: '12:30 PM Onwards',
    hallBn: 'উভয়ের নিজ নিজ পৈত্রিক নিবাস',
    hallEn: 'Respective Ancestral Homes',
    dressBn: 'ঐতিহ্যবাহী সুতি ধুতি-পাঞ্জাবি ও তাঁতের শাড়ি',
    dressEn: 'Traditional Dhoti-Panjabi & Bengali Cotton/Taant Saree',
    colorScheme: 'from-amber-800 to-amber-950',
    icon: 'utensils',
  },
  {
    id: 'gaye_holud',
    titleBn: 'গায়ে হলুদ ও সুমঙ্গল স্নান',
    titleEn: 'Gaye Holud (Turmeric & Haldi Blessing)',
    subtitleBn: 'হরিতাল ও কাঁচা হলুদের সৌরভ এবং তত্ত্ব আদান-প্রদান',
    subtitleEn: 'Applying sacred fragrant turmeric paste with traditional Tatwa gifts',
    dateBn: '২৫শে অগ্রহায়ণ, ১৪৩১ (১১ই ডিসেম্বর, ২০২৬)',
    dateEn: 'Friday, 11th December, 2026 (Morning)',
    timeBn: 'সকাল ৯:০০ ঘটিকা',
    timeEn: '9:00 AM Sharp',
    hallBn: 'উৎসব প্রাঙ্গণ ও অঙ্গন',
    hallEn: 'Courtyard & Banquet Lawn',
    dressBn: 'বাসন্তী হলুদ পাঞ্জাবি ও হলুদ পাড় লাল শাড়ি',
    dressEn: 'Basanti Yellow Silk Kurta & Traditional Yellow Saree',
    colorScheme: 'from-yellow-700 to-amber-900',
    icon: 'sparkles',
  },
  {
    id: 'bibaho',
    titleBn: 'শুভ বিবাহ ও শুভদৃষ্টি',
    titleEn: 'Shubho Bibaho (The Holy Wedding Ceremony)',
    subtitleBn: 'সাত পাক, সম্প্রদান, শুভদৃষ্টি ও সিঁদুর দান',
    subtitleEn: 'Seven rounds around sacred agni, Saat Paak, Sindoor Daan & Vedic Vows',
    dateBn: '২৫শে অগ্রহায়ণ, ১৪৩১ (১১ই ডিসেম্বর, ২০২৬)',
    dateEn: 'Friday, 11th December, 2026 (Evening)',
    timeBn: 'শুভ লগ্ন: রাত ৮:২৫ মিনিট (অতিথি সমাগম সন্ধ্যা ৬:৩০)',
    timeEn: 'Auspicious Muhurat: 8:25 PM (Guest Reception from 6:30 PM)',
    hallBn: '“রায় বাড়ি” মূল বিবাহ মণ্ডপ',
    hallEn: 'Roy Bari Grand Heritage Mandap',
    dressBn: 'রাজকীয় বেনারসী শাড়ি ও তসর সিল্কের জোড়-ধুতি',
    dressEn: 'Royal Red Benarasi Silk & Cream Tussar Silk Dhoti-Kurta',
    colorScheme: 'from-red-900 to-red-950',
    icon: 'heart-handshake',
  },
  {
    id: 'boubhat',
    titleBn: 'প্রীতিভোজ ও বউভাত (রিসেপশন)',
    titleEn: 'Boubhat & Grand Wedding Reception',
    subtitleBn: 'নববধূর ভাত-কাপড় প্রদান ও আনন্দ সান্ধ্য উৎসব',
    subtitleEn: 'Welcoming the new bride into the groom’s home with a grand gala banquet',
    dateBn: '২৭শে অগ্রহায়ণ, ১৪৩১ (১৩ই ডিসেম্বর, ২০২৬)',
    dateEn: 'Sunday, 13th December, 2026',
    timeBn: 'সন্ধ্যা ৭:০০ ঘটিকা হইতে',
    timeEn: '7:00 PM Onwards',
    hallBn: 'গ্র্যান্ড ক্রাউন ব্যাঙ্কোয়েট অ্যান্ড লন, কলকাতা',
    hallEn: 'Grand Crown Banquet & Lawns, Kolkata',
    dressBn: 'উৎসবের অভিজাত পোশাক (ইন্ডো-ওয়েস্টার্ন বা সিল্ক)',
    dressEn: 'Festive Royal Attire (Indo-Western / Tuxedo / Silk Lehengas)',
    colorScheme: 'from-purple-900 to-indigo-950',
    icon: 'crown',
  },
];

export const storyMilestones: StoryMilestone[] = [
  {
    year: '২০২১ (2021)',
    titleBn: 'প্রথম দেখা: কফি হাউস ও বইয়ের গন্ধ',
    titleEn: 'The First Encounter: College Street Coffee House',
    descBn: 'কলকাতা আন্তর্জাতিক বইমেলায় সাহিত্য আলোচনার মাঝে আকস্মিক চোখাচোখি। সেই শুরু মিষ্টি বন্ধুত্বের।',
    descEn: 'A serendipitous encounter amidst the smell of fresh books at the Kolkata Book Fair sparked a timeless conversation.',
    badgeBn: 'সূচনা পর্ব',
    badgeEn: 'The Beginning',
  },
  {
    year: '২০২৩ (2023)',
    titleBn: 'পাহাড়ের দেশে সুরভিত প্রস্তাব',
    titleEn: 'A Proposal in the Mist: Darjeeling Tea Gardens',
    descBn: 'কাঞ্চনজঙ্ঘার সোনালী সূর্যোদয়ে শিমুল ফুলের লাল আভায় অয়ন জীবনের শ্রেষ্ঠ প্রশ্নটি করেছিল শ্রেয়াকে।',
    descEn: 'Under the golden sunrise over Kanchenjunga, surrounded by tea plantations, Ayan asked the most beautiful question.',
    badgeBn: 'হৃদয় বন্ধন',
    badgeEn: 'The Yes Moment',
  },
  {
    year: '২০২৫ (2025)',
    titleBn: 'দুই পরিবারের শুভ আশীর্বাদ',
    titleEn: 'Two Families, One Harmonious Bond',
    descBn: 'মিষ্টিমুখ ও শঙ্খধ্বনির মাধ্যমে দুই পরিবারের সম্মতিতে নির্ধারিত হলো জীবনের নতুন শুভ যাত্রা।',
    descEn: 'With the blowing of the auspicious conch (Shankha) and blessings of elders, the two homes united with open hearts.',
    badgeBn: 'পাকা দেখা',
    badgeEn: 'Families United',
  },
  {
    year: '২০২৬ (2026)',
    titleBn: 'অনন্তের পথে পদার্পণ',
    titleEn: 'The Eternal Vow: Shubho Bibaho',
    descBn: 'অগ্নিকে সাক্ষী রেখে শুরু হতে চলেছে আমাদের চিরন্তন পথচলা। আপনাদের আশীর্বাদ আমাদের পাথেয়।',
    descEn: 'Stepping into forever together hand-in-hand with Vedic rituals, sacred fire, and your cherished blessings.',
    badgeBn: 'শুভ বিবাহ',
    badgeEn: 'Forever Begins',
  },
];

export const galleryPhotos: WeddingPhoto[] = [
  {
    id: 'p1',
    url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80',
    titleBn: 'ভালোবাসার প্রথম হাসি',
    titleEn: 'A Warm Smile Together',
    category: 'prewedding',
  },
  {
    id: 'p2',
    url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
    titleBn: 'লাজুক দৃষ্টি ও আনন্দ',
    titleEn: 'Grace and Joy',
    category: 'prewedding',
  },
  {
    id: 'p3',
    url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
    titleBn: 'পাহাড়ের কোলে সূর্যাস্ত',
    titleEn: 'Sunset in the Hills',
    category: 'candid',
  },
  {
    id: 'p4',
    url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
    titleBn: 'দুই পরিবারের শুভ আশীর্বাদ',
    titleEn: 'Blessings of Elders',
    category: 'family',
  },
  {
    id: 'p5',
    url: 'https://images.unsplash.com/photo-1609151162377-794fa6ec9a3f?auto=format&fit=crop&w=1000&q=80',
    titleBn: 'গায়ে হলুদের রঙ ও সুর',
    titleEn: 'Colors of Haldi Ceremony',
    category: 'ceremony',
  },
  {
    id: 'p6',
    url: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=1000&q=80',
    titleBn: 'অনন্ত পথচলার প্রতীক্ষা',
    titleEn: 'Waiting for the Big Day',
    category: 'candid',
  },
];

export const initialGuestbookEntries: RSVPSubmission[] = [
  {
    id: 'rsvp-1',
    guestName: 'ড. শুভাশিস চক্রবর্তী ও পরিবার',
    contact: '+91 98300 11223',
    attending: 'attending',
    guestCount: 3,
    ceremonies: ['bibaho', 'boubhat'],
    mealPreference: 'traditional_nonveg',
    blessingMessage: 'অয়ন ও শ্রেয়া, তোমাদের ভবিষ্যৎ দাম্পত্য জীবন সুখ, সমৃদ্ধি ও ভালোবাসায় ভরপুর হোক। অন্তরের আশীর্বাদ রইল!',
    createdAt: '২০২৬-০৯-১৫',
    syncedToGoogleSheet: true,
  },
  {
    id: 'rsvp-2',
    guestName: 'সৌভিক ব্যানার্জী (বন্ধুমহল)',
    contact: 'souvik.banerjee@gmail.com',
    attending: 'attending',
    guestCount: 2,
    ceremonies: ['gaye_holud', 'bibaho', 'boubhat'],
    mealPreference: 'traditional_nonveg',
    blessingMessage: 'আমাদের প্রিয় অয়নের বিয়ে! দারুণ আনন্দ হবে। অনেক অনেক শুভেচ্ছা দুজনকে!',
    createdAt: '২০২৬-০৯-১৮',
    syncedToGoogleSheet: true,
  },
  {
    id: 'rsvp-3',
    guestName: 'শ্রীমতি অনুরাধা রায়চৌধুরী',
    contact: '+91 98745 54321',
    attending: 'attending',
    guestCount: 2,
    ceremonies: ['bibaho'],
    mealPreference: 'pure_veg',
    blessingMessage: 'মা শ্রেয়া ও বাবা অয়নকে পরমেশ্বরের শ্রীচরণে শুভ আশীর্বাদ সমর্পণ করি। যুগল যেন সর্বদা সুস্থ থাকে।',
    createdAt: '২০২৬-০৯-২০',
    syncedToGoogleSheet: true,
  },
];
